//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int address_id { get; set; }
        public Nullable<int> source_id { get; set; }
        public string source_type { get; set; }
        public string address_type { get; set; }
        public string address_1 { get; set; }
        public string address_2 { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> city_id { get; set; }
        public string zip_code { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string web { get; set; }
        public string mobile { get; set; }
    }
}
