//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class area
    {
        public int area_id { get; set; }
        public string area_name { get; set; }
        public string area_details { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> created_company { get; set; }
        public Nullable<int> counter_man_id { get; set; }
    }
}
