//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus
    {
        public int bus_id { get; set; }
        public string bus_registration_no { get; set; }
        public string chassis_no { get; set; }
        public string registration_date { get; set; }
        public string registration_expire_date { get; set; }
        public Nullable<int> bus_type_id { get; set; }
        public Nullable<int> number_of_seats { get; set; }
        public string created_date { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> route_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<int> conductor_id { get; set; }
    }
}
