//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_type
    {
        public int bus_type_id { get; set; }
        public string bus_type_name { get; set; }
        public Nullable<int> company_id { get; set; }
        public string details { get; set; }
    }
}
