//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class control
    {
        public string control_name { get; set; }
        public Nullable<int> control_parent_id { get; set; }
        public Nullable<int> control_type_id { get; set; }
        public Nullable<int> control_sort { get; set; }
        public string control_alias { get; set; }
        public string control_controller { get; set; }
        public string control_action { get; set; }
        public Nullable<int> created_by { get; set; }
        public string created_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public string updated_date { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> Level { get; set; }
        public string icon { get; set; }
        public int control_id { get; set; }
    }
}
