//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class counter_employee_mapping
    {
        public int ce_mapping_id { get; set; }
        public Nullable<int> route_id { get; set; }
        public Nullable<int> area_id { get; set; }
        public Nullable<int> counter_man_id { get; set; }
        public string direction { get; set; }
    }
}
