//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency_conversion
    {
        public int currency_conversion_id { get; set; }
        public Nullable<int> actual_currency_id { get; set; }
        public Nullable<int> converted_currency_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<System.DateTime> currency_date { get; set; }
        public Nullable<decimal> actual_currency_unit { get; set; }
        public Nullable<decimal> converted_currency_unit { get; set; }
    }
}
