//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public string department_name { get; set; }
        public string department_abbreviation { get; set; }
        public Nullable<int> parent_department_id { get; set; }
        public Nullable<int> incharge_employee_id { get; set; }
        public string location { get; set; }
        public Nullable<int> created_by { get; set; }
        public string created_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public string updated_date { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public int department_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> branch_id { get; set; }
    }
}
