//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string emp_firstname { get; set; }
        public string emp_lastname { get; set; }
        public string emp_gender { get; set; }
        public string emp_dateofbirth { get; set; }
        public string emp_blood_group { get; set; }
        public string emp_marital_status { get; set; }
        public string emp_image_file_name { get; set; }
        public string emp_id_type { get; set; }
        public string emp_id_no { get; set; }
        public string emp_bank_title { get; set; }
        public string emp_account_number { get; set; }
        public Nullable<int> employee_role { get; set; }
        public string employee_email { get; set; }
        public string emp_code { get; set; }
        public Nullable<int> company_id { get; set; }
        public string emp_dateofjoin { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> designation_id { get; set; }
        public Nullable<int> staffgrade_id { get; set; }
        public Nullable<int> attendance_policy_id { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<int> subsection_id { get; set; }
        public int emp_id { get; set; }
        public Nullable<int> employee_id { get; set; }
    }
}
