//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPEntities : DbContext
    {
        public ERPEntities()
            : base("name=ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<address> addresses { get; set; }
        public DbSet<admin> admins { get; set; }
        public DbSet<bank> banks { get; set; }
        public DbSet<branch> branches { get; set; }
        public DbSet<brand> brands { get; set; }
        public DbSet<bus> buses { get; set; }
        public DbSet<bus_type> bus_type { get; set; }
        public DbSet<city> cities { get; set; }
        public DbSet<company> companies { get; set; }
        public DbSet<contact> contacts { get; set; }
        public DbSet<control> controls { get; set; }
        public DbSet<control_type> control_type { get; set; }
        public DbSet<country> countries { get; set; }
        public DbSet<currency_conversion> currency_conversion { get; set; }
        public DbSet<emp_contact_info> emp_contact_info { get; set; }
        public DbSet<emp_documents> emp_documents { get; set; }
        public DbSet<emp_job_details> emp_job_details { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<employee_salary> employee_salary { get; set; }
        public DbSet<experience> experiences { get; set; }
        public DbSet<hr_education> hr_education { get; set; }
        public DbSet<hr_emp_contact_info> hr_emp_contact_info { get; set; }
        public DbSet<hr_emp_documents> hr_emp_documents { get; set; }
        public DbSet<hr_emp_job_details> hr_emp_job_details { get; set; }
        public DbSet<hr_emp_shifting_user> hr_emp_shifting_user { get; set; }
        public DbSet<hr_emp_wise_attn_policy> hr_emp_wise_attn_policy { get; set; }
        public DbSet<hr_employee_salary> hr_employee_salary { get; set; }
        public DbSet<hr_experience> hr_experience { get; set; }
        public DbSet<hr_leave_application_details> hr_leave_application_details { get; set; }
        public DbSet<hr_leave_application_master> hr_leave_application_master { get; set; }
        public DbSet<hr_leave_policy> hr_leave_policy { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<role_type> role_type { get; set; }
        public DbSet<staffgrade> staffgrades { get; set; }
        public DbSet<sts_action_process> sts_action_process { get; set; }
        public DbSet<sts_approval_chain> sts_approval_chain { get; set; }
        public DbSet<sts_document_status> sts_document_status { get; set; }
        public DbSet<sts_messages> sts_messages { get; set; }
        public DbSet<sts_pagelist> sts_pagelist { get; set; }
        public DbSet<sts_pagewise_button> sts_pagewise_button { get; set; }
        public DbSet<sts_role_pagewise_button> sts_role_pagewise_button { get; set; }
        public DbSet<sts_route_sequence> sts_route_sequence { get; set; }
        public DbSet<sts_tbldesign> sts_tbldesign { get; set; }
        public DbSet<sts_tbldesigndetails> sts_tbldesigndetails { get; set; }
        public DbSet<user_permission> user_permission { get; set; }
        public DbSet<user_role_mapping> user_role_mapping { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<currency> currencies { get; set; }
        public DbSet<department> departments { get; set; }
        public DbSet<designation> designations { get; set; }
        public DbSet<subsection> subsections { get; set; }
        public DbSet<hr_payroll_salary_header> hr_payroll_salary_header { get; set; }
        public DbSet<hr_staffgrade> hr_staffgrade { get; set; }
        public DbSet<hr_leave_status_meta> hr_leave_status_meta { get; set; }
        public DbSet<hr_advance_details> hr_advance_details { get; set; }
        public DbSet<hr_approval_workflow_settings> hr_approval_workflow_settings { get; set; }
        public DbSet<hr_approval_workflow_status> hr_approval_workflow_status { get; set; }
        public DbSet<hr_attendance_policy> hr_attendance_policy { get; set; }
        public DbSet<hr_date_info> hr_date_info { get; set; }
        public DbSet<hr_month_master> hr_month_master { get; set; }
        public DbSet<hr_payroll_employee_advance> hr_payroll_employee_advance { get; set; }
        public DbSet<hr_payroll_employee_tax> hr_payroll_employee_tax { get; set; }
        public DbSet<hr_provident_fund_settings> hr_provident_fund_settings { get; set; }
        public DbSet<hr_shift_policy> hr_shift_policy { get; set; }
        public DbSet<hr_subsection> hr_subsection { get; set; }
        public DbSet<hr_unit> hr_unit { get; set; }
        public DbSet<hr_week_day> hr_week_day { get; set; }
        public DbSet<hr_year> hr_year { get; set; }
        public DbSet<job_location> job_location { get; set; }
        public DbSet<area> areas { get; set; }
        public DbSet<bus_route> bus_route { get; set; }
        public DbSet<counter_employee_mapping> counter_employee_mapping { get; set; }
        public DbSet<route_mapping> route_mapping { get; set; }
        public DbSet<bus_fare> bus_fare { get; set; }
        public DbSet<super_user> super_user { get; set; }
        public DbSet<trip_details> trip_details { get; set; }
        public DbSet<trip_master> trip_master { get; set; }
    }
}
