//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_approval_workflow_settings
    {
        public int leave_workflow_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public string emp_code { get; set; }
        public Nullable<int> step { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> super_id { get; set; }
    }
}
