//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_advance_details
    {
        public int ad_id { get; set; }
        public string ad_emp_id { get; set; }
        public Nullable<int> pea_id { get; set; }
        public string ad_year { get; set; }
        public string ad_month { get; set; }
        public Nullable<int> ad_install_no { get; set; }
        public string ad_paid_amount { get; set; }
        public string created_by { get; set; }
        public Nullable<int> created_at { get; set; }
        public string last_updated_by { get; set; }
        public Nullable<int> last_updated_at { get; set; }
        public string advance_total { get; set; }
        public string advance_realized { get; set; }
        public string advance_due { get; set; }
        public string amount_per_installment { get; set; }
    }
}
