//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_date_info
    {
        public int dates_id { get; set; }
        public Nullable<int> master_id { get; set; }
        public Nullable<int> day_type_id { get; set; }
        public Nullable<int> holiday_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> company_id { get; set; }
        public string day_title { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
