//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_emp_documents
    {
        public string file_name { get; set; }
        public string file_description { get; set; }
        public string file_location { get; set; }
        public Nullable<int> employee_id { get; set; }
        public int emp_documents_id { get; set; }
    }
}
