//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_education
    {
        public int education_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string degree_name { get; set; }
        public string institute { get; set; }
        public Nullable<int> passing_year { get; set; }
        public string result { get; set; }
    }
}
