//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_emp_shifting_user
    {
        public int emp_shift_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> shift_id { get; set; }
        public int emp_id { get; set; }
        public string emp_code { get; set; }
        public Nullable<System.DateTime> schedule_date { get; set; }
    }
}
