//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_emp_wise_attn_policy
    {
        public int emp_wise_attnd_policy_id { get; set; }
        public Nullable<int> attendance_policy_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> company_id { get; set; }
    }
}
