//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_emp_job_details
    {
        public Nullable<int> company_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> designation_id { get; set; }
        public Nullable<int> staffgrade_id { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> created_by { get; set; }
        public string created_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public string updated_date { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string emp_prop_confirmation_date { get; set; }
        public Nullable<int> subsection_id { get; set; }
        public Nullable<int> job_location_id { get; set; }
        public string emp_supervisor { get; set; }
        public string emp_reporting_method { get; set; }
        public Nullable<int> attendance_policy_id { get; set; }
        public Nullable<int> unit_id { get; set; }
        public int emp_job_details_id { get; set; }
    }
}
