//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_emp_contact_info
    {
        public Nullable<int> city_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public string present_address { get; set; }
        public string permanent_address { get; set; }
        public Nullable<int> zip_code { get; set; }
        public string emp_email { get; set; }
        public string emp_phone { get; set; }
        public string emp_mobile { get; set; }
        public Nullable<int> employee_id { get; set; }
        public int emp_contact_info_id { get; set; }
        public string emergency_contact_name { get; set; }
        public string emergency_contact_id { get; set; }
        public string emergency_contact_address { get; set; }
        public string emergency_contact_email { get; set; }
        public string emergency_contact_mobile { get; set; }
        public string emergency_contact_relation { get; set; }
    }
}
