//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_leave_application_master
    {
        public int leave_application_master_id { get; set; }
        public string application_date { get; set; }
        public Nullable<int> company_id { get; set; }
        public string emp_code { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string no_of_days { get; set; }
        public string is_approved { get; set; }
        public string status { get; set; }
        public string review_date { get; set; }
        public Nullable<int> reviewed_by { get; set; }
        public string reasons { get; set; }
        public string last_updated_at { get; set; }
        public Nullable<int> last_updated_by { get; set; }
        public string created_at { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> leave_policy_id { get; set; }
    }
}
