//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_leave_policy
    {
        public int leave_policy_id { get; set; }
        public string leave_policy_title { get; set; }
        public string lp_short_code { get; set; }
        public Nullable<bool> applicable_to_all { get; set; }
        public Nullable<int> available_after_months { get; set; }
        public Nullable<bool> leave_cut_applicable { get; set; }
        public Nullable<bool> pro_rate_basis { get; set; }
        public Nullable<bool> carry_forward { get; set; }
        public Nullable<int> max_carry_forward { get; set; }
        public Nullable<bool> weekend_holiday_count { get; set; }
        public string total_days { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> company_id { get; set; }
    }
}
