//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_leave_status_meta
    {
        public int leave_status_meta_id { get; set; }
        public string emp_code { get; set; }
        public Nullable<int> leave_type_id { get; set; }
        public string total_days { get; set; }
        public string availed_days { get; set; }
        public string remaining_days { get; set; }
        public Nullable<int> year { get; set; }
        public string created_by { get; set; }
        public string created_at { get; set; }
        public string last_updated_by { get; set; }
        public string last_updated_at { get; set; }
        public Nullable<int> carry_forward_flag { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> emp_id { get; set; }
    }
}
