//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_leave_application_details
    {
        public int leave_application_details_id { get; set; }
        public Nullable<int> leave_application_master_id { get; set; }
        public Nullable<int> leave_type_id { get; set; }
        public string details_date { get; set; }
        public string details_no_of_days { get; set; }
        public string status { get; set; }
        public string remarks { get; set; }
        public string emp_code { get; set; }
        public string is_half { get; set; }
        public string day_part { get; set; }
        public string replacement_date { get; set; }
        public Nullable<int> emp_id { get; set; }
    }
}
