//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_month_master
    {
        public int month_master_id { get; set; }
        public Nullable<int> month_id { get; set; }
        public string month { get; set; }
        public Nullable<int> year_id { get; set; }
        public Nullable<int> attendance_policy_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
