//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_provident_fund_settings
    {
        public int pf_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string pf_start { get; set; }
        public string pf_after_1y { get; set; }
        public string pf_after_2y { get; set; }
        public string pf_after_3y { get; set; }
        public Nullable<int> salary_component_id { get; set; }
        public string pf_main { get; set; }
    }
}
