//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_payroll_salary_header
    {
        public int psh_id { get; set; }
        public string psh_title { get; set; }
        public string psh_display_on { get; set; }
        public Nullable<bool> psh_is_monthly { get; set; }
        public Nullable<bool> psh_is_optional { get; set; }
        public string psh_added_on { get; set; }
        public string psh_added_by { get; set; }
        public string psh_updated_on { get; set; }
        public string psh_updated_by { get; set; }
        public Nullable<bool> psh_is_required { get; set; }
        public string psh_show_in_tmp_mod { get; set; }
        public string psh_is_gross { get; set; }
        public Nullable<int> company_id { get; set; }
    }
}
