//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_location
    {
        public int job_location_id { get; set; }
        public string job_location_title { get; set; }
        public string created_at { get; set; }
        public Nullable<int> created_by { get; set; }
        public string updated_at { get; set; }
        public Nullable<int> updated_by { get; set; }
    }
}
