//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staffgrade
    {
        public int staffgrade_id { get; set; }
        public string staffgrade_title { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> employee_id { get; set; }
    }
}
