//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sts_messages
    {
        public int msg_id { get; set; }
        public string message { get; set; }
        public string attachment { get; set; }
        public Nullable<int> sender { get; set; }
        public string recipient_role { get; set; }
        public string table { get; set; }
        public Nullable<int> is_viewed { get; set; }
        public Nullable<int> f_id { get; set; }
        public Nullable<int> wkorder_id { get; set; }
        public string status { get; set; }
        public string customer_po { get; set; }
        public string erp_number { get; set; }
        public string msg_time { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> recipient { get; set; }
        public string msg_type { get; set; }
        public Nullable<int> is_replied { get; set; }
        public string order_code { get; set; }
        public Nullable<int> product_id { get; set; }
    }
}
