//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sts_pagewise_button
    {
        public int pagewise_button_id { get; set; }
        public Nullable<int> process_id { get; set; }
        public Nullable<int> page_id { get; set; }
        public string status { get; set; }
        public Nullable<int> company_id { get; set; }
    }
}
