//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sts_document_status
    {
        public int doc_status_id { get; set; }
        public string status { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> is_rejected { get; set; }
        public Nullable<int> is_accepted { get; set; }
        public Nullable<int> is_waiting { get; set; }
        public Nullable<int> company_id { get; set; }
    }
}
