//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sts_pagelist
    {
        public int page_id { get; set; }
        public string page_name { get; set; }
        public string status { get; set; }
        public Nullable<int> company_id { get; set; }
    }
}
