//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip_master
    {
        public int trip_master_id { get; set; }
        public Nullable<int> bus_id { get; set; }
        public string date { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> route_id { get; set; }
        public Nullable<int> area_id { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<int> trip_count { get; set; }
        public Nullable<long> time { get; set; }
        public string direction { get; set; }
    }
}
