//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_permission
    {
        public int user_permission_id { get; set; }
        public Nullable<int> user_au_id { get; set; }
        public Nullable<int> user_control_id { get; set; }
        public Nullable<int> user_permission_status { get; set; }
        public Nullable<int> user_role_id { get; set; }
    }
}
