using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using ERPApi.Models;
namespace ERPApi.Controllers
{
    public class AdminOperationController : ApiController
    {


        public HttpResponseMessage AutoGeneratedBomSetupForProduct()
        {
             //ERPEntities _entities = new ERPEntities();


            return new HttpResponseMessage();
            
        }
    }
}